spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      platform: postgres

server:
  port: 8089

app:
  cors:
    enable: true
    pathPattern: "/**"
    origins: "*"
    credentials: true
    methods: GET, POST, PUT, DELETE